# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 23:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('balance_updates', '0002_auto_20160530_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceupdate',
            name='canceled_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canceled_balances', to=settings.AUTH_USER_MODEL),
        ),
    ]
