# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 13:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name=b'Name')),
                ('time_needed', models.PositiveSmallIntegerField(default=0)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('number_of_visit', models.PositiveSmallIntegerField(default=1, verbose_name=b'Number Of Visit')),
                ('number_of_people', models.PositiveSmallIntegerField(default=1, verbose_name=b'Number Of People')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='treatments.Treatment')),
            ],
        ),
    ]
