# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 13:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, b'Created'), (2, b'Confirmed'), (3, b'In Progress'), (4, b'Completed'), (5, b'Canceled')], default=1)),
                ('code', models.CharField(blank=True, db_index=True, default=None, max_length=12, null=True, unique=True)),
                ('promotion_code', models.CharField(blank=True, default=b'', max_length=24)),
                ('price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('completed_paid', models.BooleanField(default=False)),
                ('total_payment', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_booking', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='services.Service')),
            ],
        ),
    ]
