# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 15:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('photo_url', models.CharField(max_length=255)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, b'New'), (2, b'Accepted'), (3, b'Rejected')], default=1)),
                ('notes', models.TextField(blank=True, default=b'')),
                ('correction_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_confirmations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Created'), (2, b'Confirmed'), (3, b'In Progress'), (4, b'Reversed Balance'), (5, b'Completed'), (6, b'Canceled')], default=1),
        ),
        migrations.AddField(
            model_name='orderconfirmation',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_confirmations', to='orders.Order'),
        ),
    ]
