# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 13:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderconfirmation_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconfirmation',
            name='correction_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_confirmations', to=settings.AUTH_USER_MODEL),
        ),
    ]
