# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 23:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20160602_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unique_price',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
