# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 15:14
from __future__ import unicode_literals

from django.db import migrations
import rumahtotok.core.utils
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20160604_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentconfirmation',
            name='photo',
            field=thumbnails.fields.ImageField(blank=True, default=b'', upload_to=rumahtotok.core.utils.FilenameGenerator(prefix=b'payment_confirmations')),
        ),
    ]
