# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_paymentconfirmation_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='promotion_code',
            field=models.CharField(blank=True, default=b'', max_length=24, null=True),
        ),
    ]
