# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 15:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20160622_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_booking',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
