# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_completed_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='balance_reversed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Created'), (2, b'Confirmed'), (3, b'In Progress'), (4, b'Completed'), (5, b'Canceled')], default=1),
        ),
    ]
