# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('discount_percentage', models.FloatField(blank=True, null=True)),
                ('discount_nominal', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, b'One Time'), (2, b'Unlimited Use'), (3, b'First Time User')])),
                ('services', models.ManyToManyField(blank=True, related_name='promotions', to='services.Service')),
            ],
        ),
    ]
