# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 22:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20160530_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='balance_used',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
