# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 23:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_balance_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='type',
        ),
        migrations.AlterField(
            model_name='payment',
            name='value',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
