# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20160530_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Cash'), (2, b'Transfer'), (3, b'Balance'), (4, b'Cash and Balance')], default=1),
        ),
    ]
