# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-21 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import retribution.apps.users.models
import retribution.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(blank=True, db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, db_index=True, default=None, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('mobile_number', models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True, validators=[retribution.core.validators.validate_mobile_number], verbose_name='Mobile Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Employee'), (2, 'Customer'), (3, 'Therapist')], default=2)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', retribution.apps.users.models.CustomUserManager()),
            ],
        ),
    ]
