# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-14 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_destinations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='destinations',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
