# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, b'New'), (2, b'Assigned'), (3, b'Completed'), (4, b'Canceled')], default=1)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('duration', models.PositiveSmallIntegerField(default=0)),
                ('code', models.CharField(blank=True, db_index=True, max_length=6)),
                ('notes', models.TextField(blank=True, default=b'')),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1 - Bad'), (2, b'2'), (3, b'3 - Average'), (4, b'4'), (5, b'5 - Best')], null=True)),
            ],
        ),
    ]
