# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20160530_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='platform',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'API (Mobile)'), (2, b'Backoffice')], null=True),
        ),
    ]
