# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(null=True),
            preserve_default=False,
        ),
    ]
