# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 13:16
from __future__ import unicode_literals

from django.db import migrations
import rumahtotok.core.utils
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='icon',
            field=thumbnails.fields.ImageField(blank=True, default=b'', upload_to=rumahtotok.core.utils.FilenameGenerator(prefix=b'treatment_icon')),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='photo',
            field=thumbnails.fields.ImageField(blank=True, default=b'', upload_to=rumahtotok.core.utils.FilenameGenerator(prefix=b'treatment')),
        ),
    ]
