# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0002_auto_20160609_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
