# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 13:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
