# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0002_therapist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='max_booking',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
