# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 03:16
from __future__ import unicode_literals

from django.db import migrations
import rumahtotok.core.utils
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image4',
            field=thumbnails.fields.ImageField(blank=True, default=b'', upload_to=rumahtotok.core.utils.FilenameGenerator(prefix=b'banner')),
        ),
    ]
