# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='BBM_pin',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
