# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20160621_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='max_female_booking',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='store',
            name='max_male_booking',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
