# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-21 16:45
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(db_index=True, max_length=254)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, b'Local'), (2, b'Mancanegara')], default=1)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('transport_id', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Nomor Kendaraan')),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('transport', models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Motor'), (2, b'Mobile')], null=True)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retributions', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retributions', to='destinations.Destination')),
            ],
        ),
    ]
