# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-23 14:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retributions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retribution',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='retribution',
            name='transport',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Motor'), (2, b'Mobil')], null=True),
        ),
    ]
