# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import rumahtotok.apps.users.models
import rumahtotok.core.utils
import rumahtotok.core.validators
import thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(blank=True, db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, default=None, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('mobile_number', models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True, validators=[rumahtotok.core.validators.validate_mobile_number], verbose_name='Mobile Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('notes', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('lat', models.FloatField(blank=True, default=None, null=True)),
                ('long', models.FloatField(blank=True, default=None, null=True)),
                ('referral_code', models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True)),
                ('balance', models.FloatField(default=0)),
                ('type', models.PositiveSmallIntegerField(default=2)),
                ('photo', thumbnails.fields.ImageField(blank=True, help_text='Image must be 300x300 in dimension', upload_to=rumahtotok.core.utils.FilenameGenerator(prefix='users'))),
                ('gcm_key', models.CharField(blank=True, default='', max_length=254)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', rumahtotok.apps.users.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_until', models.DateTimeField(db_index=True, verbose_name='Valid until')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='confirmation',
            unique_together=set([('mobile_number', 'code')]),
        ),
    ]
