# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Employee'), (2, 'Customer'), (3, 'Therapist')], default=2),
        ),
    ]
