# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160602_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_from',
            field=models.PositiveSmallIntegerField(choices=[(1, 'API'), (2, 'Backoffice')], default=2),
        ),
    ]
