# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 01:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmation',
            name='valid_until',
            field=models.DateTimeField(verbose_name='Valid until'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL),
        ),
    ]
